export const ROLES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  PRINCIPAL: 'principal',
  TEACHER: 'teacher',
  ACCOUNTANT: 'accountant',
  STUDENT: 'student',
  PARENT: 'parent',
} as const

export type Role = (typeof ROLES)[keyof typeof ROLES]

export const ROLE_LABELS: Record<Role, string> = {
  [ROLES.SUPER_ADMIN]: 'Super Admin',
  [ROLES.ADMIN]: 'Admin',
  [ROLES.PRINCIPAL]: 'Principal',
  [ROLES.TEACHER]: 'Teacher',
  [ROLES.ACCOUNTANT]: 'Accountant',
  [ROLES.STUDENT]: 'Student',
  [ROLES.PARENT]: 'Parent',
}

export const PERMISSIONS = {
  // Student Management
  STUDENTS_VIEW: 'students:view',
  STUDENTS_CREATE: 'students:create',
  STUDENTS_EDIT: 'students:edit',
  STUDENTS_DELETE: 'students:delete',
  STUDENTS_EXPORT: 'students:export',

  // Teacher/Staff Management
  TEACHERS_VIEW: 'teachers:view',
  TEACHERS_CREATE: 'teachers:create',
  TEACHERS_EDIT: 'teachers:edit',
  TEACHERS_DELETE: 'teachers:delete',

  STAFF_VIEW: 'staff:view',
  STAFF_CREATE: 'staff:create',
  STAFF_EDIT: 'staff:edit',
  STAFF_DELETE: 'staff:delete',

  // Attendance
  ATTENDANCE_VIEW: 'attendance:view',
  ATTENDANCE_VIEW_OWN: 'attendance:view:own',
  ATTENDANCE_MARK: 'attendance:mark',
  ATTENDANCE_EDIT: 'attendance:edit',
  ATTENDANCE_REPORTS: 'attendance:reports',

  // Fees
  FEES_VIEW: 'fees:view',
  FEES_VIEW_OWN: 'fees:view:own',
  FEES_COLLECT: 'fees:collect',
  FEES_MANAGE: 'fees:manage',
  FEES_REPORTS: 'fees:reports',

  // Exams
  EXAMS_VIEW: 'exams:view',
  EXAMS_VIEW_OWN: 'exams:view:own',
  EXAMS_CREATE: 'exams:create',
  EXAMS_RESULTS_ENTER: 'exams:results:enter',
  EXAMS_RESULTS_VERIFY: 'exams:results:verify',

  // Salary
  SALARY_VIEW_OWN: 'salary:view:own',
  SALARY_VIEW_ALL: 'salary:view:all',
  SALARY_MANAGE: 'salary:manage',
  SALARY_PROCESS: 'salary:process',

  // Reports
  REPORTS_VIEW: 'reports:view',
  REPORTS_VIEW_OWN: 'reports:view:own',
  REPORTS_GENERATE: 'reports:generate',

  // WhatsApp
  WHATSAPP_VIEW: 'whatsapp:view',
  WHATSAPP_SEND: 'whatsapp:send',
  WHATSAPP_MANAGE: 'whatsapp:manage',

  // Settings
  SETTINGS_VIEW: 'settings:view',
  SETTINGS_MANAGE: 'settings:manage',
  USERS_MANAGE: 'users:manage',

  // Dashboard
  DASHBOARD_VIEW: 'dashboard:view',
  DASHBOARD_ADMIN: 'dashboard:admin',
} as const

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]

// Role-Permission Mapping
export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),

  [ROLES.ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_ADMIN,
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.STUDENTS_CREATE,
    PERMISSIONS.STUDENTS_EDIT,
    PERMISSIONS.STUDENTS_DELETE,
    PERMISSIONS.STUDENTS_EXPORT,
    PERMISSIONS.TEACHERS_VIEW,
    PERMISSIONS.TEACHERS_CREATE,
    PERMISSIONS.TEACHERS_EDIT,
    PERMISSIONS.TEACHERS_DELETE,
    PERMISSIONS.STAFF_VIEW,
    PERMISSIONS.STAFF_CREATE,
    PERMISSIONS.STAFF_EDIT,
    PERMISSIONS.STAFF_DELETE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.ATTENDANCE_EDIT,
    PERMISSIONS.ATTENDANCE_REPORTS,
    PERMISSIONS.FEES_VIEW,
    PERMISSIONS.FEES_COLLECT,
    PERMISSIONS.FEES_MANAGE,
    PERMISSIONS.FEES_REPORTS,
    PERMISSIONS.EXAMS_VIEW,
    PERMISSIONS.EXAMS_CREATE,
    PERMISSIONS.EXAMS_RESULTS_ENTER,
    PERMISSIONS.EXAMS_RESULTS_VERIFY,
    PERMISSIONS.SALARY_VIEW_ALL,
    PERMISSIONS.SALARY_MANAGE,
    PERMISSIONS.SALARY_PROCESS,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.WHATSAPP_VIEW,
    PERMISSIONS.WHATSAPP_SEND,
    PERMISSIONS.WHATSAPP_MANAGE,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.USERS_MANAGE,
  ],

  [ROLES.PRINCIPAL]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_ADMIN,
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.STUDENTS_EXPORT,
    PERMISSIONS.TEACHERS_VIEW,
    PERMISSIONS.STAFF_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_REPORTS,
    PERMISSIONS.FEES_VIEW,
    PERMISSIONS.FEES_REPORTS,
    PERMISSIONS.EXAMS_VIEW,
    PERMISSIONS.EXAMS_RESULTS_VERIFY,
    PERMISSIONS.SALARY_VIEW_ALL,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.WHATSAPP_VIEW,
    PERMISSIONS.WHATSAPP_SEND,
    PERMISSIONS.SETTINGS_VIEW,
  ],

  [ROLES.TEACHER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.EXAMS_VIEW,
    PERMISSIONS.EXAMS_RESULTS_ENTER,
    PERMISSIONS.SALARY_VIEW_OWN,
    PERMISSIONS.REPORTS_VIEW,
  ],

  [ROLES.ACCOUNTANT]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.FEES_VIEW,
    PERMISSIONS.FEES_COLLECT,
    PERMISSIONS.FEES_MANAGE,
    PERMISSIONS.FEES_REPORTS,
    PERMISSIONS.SALARY_VIEW_ALL,
    PERMISSIONS.SALARY_MANAGE,
    PERMISSIONS.SALARY_PROCESS,
  ],

  [ROLES.STUDENT]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW_OWN,
    PERMISSIONS.FEES_VIEW_OWN,
    PERMISSIONS.EXAMS_VIEW_OWN,
    PERMISSIONS.REPORTS_VIEW_OWN,
  ],

  [ROLES.PARENT]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW_OWN,
    PERMISSIONS.FEES_VIEW_OWN,
    PERMISSIONS.EXAMS_VIEW_OWN,
    PERMISSIONS.REPORTS_VIEW_OWN,
  ],
}
